baseURL = "https://unruffled-mahavira-a44200.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "OrderMatch Universe"
[markup.goldmark.renderer]
unsafe = true
[menu]
footer_right = []
[[menu.footer_left]]
URL = "technology"
name = "Our Technology"
weight = "2"
[[menu.footer_left]]
URL = "contact"
name = "Contact Us"
weight = "1"
[[menu.footer_middle]]
URL = "pricing"
name = "Licensing"
weight = ""
[[menu.footer_middle]]
URL = "marketplaces"
name = "Marketplaces"
weight = "2"
[[menu.main]]
URL = "marketplaces"
name = "Marketplaces"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
URL = "pricing"
name = "Licensing"
weight = 3
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "OrderMatchUniverseâ„¢ 2020"
description = "This is meta description"
footer_content = "An enterprise-class software for the creation and operation of an online marketplace."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
logo = "/images/ordermatch-universe-logo.png"
logo_width = "400px"
social = []
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "https://use.fontawesome.com/7186055a8d.js"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
